export enum CMDS {
	CMD_INCREASELIST = 'CMD_INCREASELIST',
	CMD_FOLLOWLIST = 'CMD_FOLLOWLIST',
	CMD_HOTLIST = 'CMD_HOTLIST',
	CMD_SELFCOIN = 'CMD_SELFCOIN',
	CMD_COINPAGE = 'CMD_COINPAGE',
	CMD_SETTING = 'CMD_SETTING',
	CMD_CHANGE_SETTING = 'CMD_CHANGE_SETTING',
	CMD_NEWS = 'CMD_NEWS',
	CMD_NEWSFLASH = 'CMD_NEWSFLASH',
	CMD_SEARCH = 'CMD_SEARCH',
	CMD_CHANGE_SELFCOIN = 'CMD_CHANGE_SELFCOIN',
	CMD_KLINE = 'CMD_KLINE',
	CMD_CUSTOMCOIN = 'CMD_CUSTOMCOIN',
	CMD_COINNEWS = 'CMD_COINNEWS',
}

export enum CMDS_PAGE {
	CMD_GET_SETTING = 'CMD_GET_SETTING',
}

export enum NewsType {
	HighLight = 124,
	DeFi = 138,
	NFT = 163,
	Market = 116,
	Mining = 139,
	Entry = 120,
}

export enum WorkerType {
	Start = 'start',
	Close = 'close',
}
