/*
 * @Date: 2021-01-16 11:57:39
 * @LastEditors: elegantYu
 * @LastEditTime: 2021-06-16 16:24:33
 * @Description: 主题色
 */
import colour from '@Styles/color';

export const light = {
	bg: colour.whitef7,
	panelBg: colour.white,
	boldFont: colour.black15,
	sidebarShadow: colour.shadowDark,
	sidebar: colour.white,
	increase: colour.red,
	decrease: colour.green,
	bannerDesc: colour.grey93,
	bannerHover: colour.whitef7,
	tabFont: colour.grey8f,
	tabFontHover: colour.blue,
	tabTip: colour.white,
	tabTipBg: colour.black85,
	tableHead: colour.grey93,
	tableSort: colour.blue,
	tdTitle: colour.black15,
	tdDesc: colour.grey93,
	tdType: colour.whitedd,
	tdBorder: colour.whitef8,
	tdHover: colour.bluef6,
	rateFont: colour.white,
	volumeFont: colour.blue26,
	volumeBg: colour.bluef0,
	quickBtnBg: colour.white,

	title: colour.grey53,
	titleBorder: colour.whitef8,
	desc: colour.whitecc,
	ratio: colour.grey,
	ratioBg: colour.whiteee,
	ratioActive: colour.white,
	ratioActiveBg: colour.blue00,
	ratioBgHover: colour.whitee0,
	ratioActiveBgHover: colour.blue41,

	tabBorder: colour.whitef8,
	newsBorder: colour.whited4,
	newsItemTitle: colour.black15,
	newsItemDesc: colour.grey93,
	newsItemAvatar: colour.whitee0,
	newsItemTime: colour.grey93,
	newsAttr: colour.white,
	newsTitle: colour.black25,
	newsGrade4: colour.yellowf1,
	newsGrade5: colour.redd4,
	newsTitleHover: colour.blue00,

	search: colour.grey,
	searchIcon: colour.grey8f,
	searchEmpty: colour.grey8f,

	tradeHeadDesc: colour.grey93,
	tradeBlack: colour.black15,
	tradeDrawer: colour.blue,
	tradeDrawerBg: colour.white,
	tradeDrawerGroup: colour.white,

	noticeName: colour.black15,
	noticePlat: colour.black25,
	noticeLink: colour.blue26,
	noticeLinkHover: colour.blue00,
	noticeUsd: colour.black15,
	noticeDesc: colour.grey93,
	noticeBorder: colour.whiteF2,
	noticePlace: colour.whitecc,
	noticeTip: colour.grey8f,
	noticeInput: colour.blue3d,
	noticeBtn: colour.white,
	noticeBtnBg: colour.whited1,
	noticeBtnHover: colour.blue3d,
	noticeTab: colour.grey93,
	noticeItem: colour.black15,
	decreaseBg: colour.greene7,
	increaseBg: colour.redf7,
	noticeEmptyIcon: colour.whited4,
	noticeEmptyBtn: colour.blue26,
	noticeEmptyBtnBg: colour.bluef6,
	noticeEmptyDesc: colour.greyc8,

	helpQuestion: colour.black15,
	helpAnswer: colour.grey66,

	progressBg: colour.whitede,
	progressBtn: colour.white,
	progressActive: colour.blue00,
	progressText: colour.grey99,
	badgeBg: colour.whiteee,
	badgeColor: colour.white,
	badgeActive: colour.blue00,
	badgeTextColor: colour.black15,

	aboutTitle: colour.black15,

	updateBg: colour.white,
	updateTitle: colour.black15,
	updateDesc: colour.grey,
	updateClose: colour.grey99,
	updateLink: colour.blue,

	loading: colour.whitef0,
	loadingFore: colour.whitede,
	error: colour.grey,
	caret: colour.blue26,
	pink: colour.pink,
	yellow: colour.yellow,
	blue: colour.blue00,
	toast: colour.white,
};

export const lightReverse = {
	...light,
	increase: colour.green,
	decrease: colour.red,
	decreaseBg: colour.redf7,
	increaseBg: colour.greene7,
};

export const dark = {
	bg: colour.black0a,
	panelBg: colour.black151e,
	boldFont: colour.whited4,
	sidebarShadow: colour.shadowDark,
	sidebar: colour.blue1a,
	increase: colour.rede2,
	decrease: colour.green0b,
	bannerDesc: colour.grey51,
	bannerHover: colour.black0a,
	tabFont: colour.whitecf,
	tabFontHover: colour.blue3d,
	tabTip: colour.white,
	tabTipBg: colour.black85,
	tableHead: colour.grey99,
	tableSort: colour.blue3d,
	tdTitle: colour.whited4,
	tdDesc: colour.grey51,
	tdType: colour.whitedd,
	tdBorder: colour.blue0b,
	tdHover: colour.black0c,
	rateFont: colour.white,
	volumeFont: colour.blue26,
	volumeBg: colour.bluef0,
	quickBtnBg: colour.blue31,

	title: colour.whitecc,
	titleBorder: colour.grey44,
	desc: colour.grey66,
	ratio: colour.grey,
	ratioBg: colour.whiteee,
	ratioActive: colour.white,
	ratioActiveBg: colour.blue00,
	ratioBgHover: colour.whitee0,
	ratioActiveBgHover: colour.blue41,

	tabBorder: colour.blue0b,
	newsBorder: colour.grey,
	newsItemTitle: colour.whited4,
	newsItemDesc: colour.grey99,
	newsItemAvatar: colour.whitee0,
	newsItemTime: colour.grey99,
	newsAttr: colour.white,
	newsTitle: colour.whitecc,
	newsGrade4: colour.yellowf1,
	newsGrade5: colour.rede2,
	newsTitleHover: colour.blue00,

	search: colour.whitecf,
	searchIcon: colour.grey8f,
	searchEmpty: colour.grey8f,

	tradeHeadDesc: colour.grey93,
	tradeBlack: colour.whitecf,
	tradeDrawer: colour.blueb8,
	tradeDrawerBg: colour.blue31,
	tradeDrawerGroup: colour.blue21,

	noticeName: colour.greycf,
	noticePlat: colour.grey99,
	noticeLink: colour.blue26,
	noticeLinkHover: colour.blue00,
	noticeUsd: colour.greycf,
	noticeDesc: colour.grey70,
	noticeBorder: colour.blue25,
	noticePlace: colour.grey44,
	noticeTip: colour.grey8f,
	noticeInput: colour.blue3d,
	noticeBtn: colour.bluef0,
	noticeBtnBg: colour.grey44,
	noticeBtnHover: colour.blue3d,
	noticeTab: colour.grey71,
	noticeItem: colour.greycf,
	decreaseBg: colour.greene7,
	increaseBg: colour.redf7,
	noticeEmptyIcon: colour.grey44,
	noticeEmptyBtn: colour.blue26,
	noticeEmptyBtnBg: colour.black0a,
	noticeEmptyDesc: colour.grey44,

	helpQuestion: colour.whiteee,
	helpAnswer: colour.whitecf,

	progressBg: colour.whitede,
	progressBtn: colour.white,
	progressActive: colour.blue00,
	progressText: colour.grey99,
	badgeBg: colour.white,
	badgeColor: colour.white,
	badgeActive: colour.blue00,
	badgeTextColor: colour.white,

	aboutTitle: colour.whitede,

	updateBg: colour.black0a,
	updateTitle: colour.whiteee,
	updateDesc: colour.whitecf,
	updateClose: colour.whitecf,
	updateLink: colour.blue41,

	loading: colour.blue21,
	loadingFore: colour.blue31,
	error: colour.grey,
	caret: colour.blue26,
	pink: colour.pink,
	yellow: colour.yellow,
	blue: colour.blue00,
	toast: colour.white,
};

export const darkReverse = {
	...dark,
	increase: colour.green0b,
	decrease: colour.rede2,
};
